project_id = "jeykzfzrkegzulvzqzxt"

[functions.transcribe]
verify_jwt = false

[functions.summarize]
verify_jwt = false

[functions.ask]
verify_jwt = false

[functions.scribe-token]
verify_jwt = false
